twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
#        - 'bootstrap_4_layout.html.twig'
#        - 'form_table_layout.html.twig'
        - 'bootstrap_4_horizontal_layout.html.twig'
    globals:
        nom:  BabaCoolCar
        contenu:  Est une plateforme de covoiturage qui met en relation passagers et conducteurs prêts à partager leur trajet en voiture pour leur permettre d'aller partout dans le pays à moindre coût et en toute convivialité.
        tel:  +224 yyy xxx zzz
        mail: contact@babacoolcar.fr
        live: Besoin d'aide en live ?